# Generated by Django 4.2.3 on 2023-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device_model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='employee_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
